# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 662e7cd2e75e2fb712ccdb93b1f7bf64af063601c9ef2f3f9d3ed293e21d3e6fb0f9cd8c5f3db17150b9bd4ebc93af0531be45d1db0126ed5b45957c60ae33d3

test:
  secret_key_base: cc46a454e4afb97ea1de8bcb5cbea881e43e019059ea15fbbcccdd8d727067549a3d388ab5d4072eeadd35db085abb894e6aad695bb16c72f6ca0ac9fd2e3441

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
